-- SSF Kerala 2025 canonical English program names
-- Updates programs.name_en only (name_ml untouched). Keyed by code.
-- Idempotent: re-running is a no-op once applied.
BEGIN;
UPDATE programs SET name_en = 'Elocution (Malayalam)' WHERE code = 'P-076' AND name_en IS DISTINCT FROM 'Elocution (Malayalam)';
UPDATE programs SET name_en = 'Elocution (Arabic)' WHERE code = 'P-077' AND name_en IS DISTINCT FROM 'Elocution (Arabic)';
UPDATE programs SET name_en = 'Elocution (English)' WHERE code = 'P-078' AND name_en IS DISTINCT FROM 'Elocution (English)';
UPDATE programs SET name_en = 'Poem Making' WHERE code = 'P-079' AND name_en IS DISTINCT FROM 'Poem Making';
UPDATE programs SET name_en = 'Story Writing' WHERE code = 'P-080' AND name_en IS DISTINCT FROM 'Story Writing';
UPDATE programs SET name_en = 'Essay Writing (Malayalam)' WHERE code = 'P-082' AND name_en IS DISTINCT FROM 'Essay Writing (Malayalam)';
UPDATE programs SET name_en = 'Essay Writing (Arabic)' WHERE code = 'P-083' AND name_en IS DISTINCT FROM 'Essay Writing (Arabic)';
UPDATE programs SET name_en = 'Madhu Gana Rachana' WHERE code = 'P-085' AND name_en IS DISTINCT FROM 'Madhu Gana Rachana';
UPDATE programs SET name_en = 'Translation (Arabic)' WHERE code = 'P-087' AND name_en IS DISTINCT FROM 'Translation (Arabic)';
UPDATE programs SET name_en = 'Calligraphy (Arabic)' WHERE code = 'P-088' AND name_en IS DISTINCT FROM 'Calligraphy (Arabic)';
UPDATE programs SET name_en = 'Hadees Musabaqa' WHERE code = 'P-090' AND name_en IS DISTINCT FROM 'Hadees Musabaqa';
UPDATE programs SET name_en = 'AI Poem Making' WHERE code = 'P-091' AND name_en IS DISTINCT FROM 'AI Poem Making';
UPDATE programs SET name_en = 'Hamd (Urdu)' WHERE code = 'P-097' AND name_en IS DISTINCT FROM 'Hamd (Urdu)';
UPDATE programs SET name_en = 'Poem Recitation (English)' WHERE code = 'P-098' AND name_en IS DISTINCT FROM 'Poem Recitation (English)';
UPDATE programs SET name_en = 'Elocution (Malayalam)' WHERE code = 'P-099' AND name_en IS DISTINCT FROM 'Elocution (Malayalam)';
UPDATE programs SET name_en = 'Elocution (English)' WHERE code = 'P-100' AND name_en IS DISTINCT FROM 'Elocution (English)';
UPDATE programs SET name_en = 'Elocution (Urdu)' WHERE code = 'P-101' AND name_en IS DISTINCT FROM 'Elocution (Urdu)';
UPDATE programs SET name_en = 'Poem Making' WHERE code = 'P-103' AND name_en IS DISTINCT FROM 'Poem Making';
UPDATE programs SET name_en = 'Poem Making (English)' WHERE code = 'P-104' AND name_en IS DISTINCT FROM 'Poem Making (English)';
UPDATE programs SET name_en = 'Story Writing' WHERE code = 'P-105' AND name_en IS DISTINCT FROM 'Story Writing';
UPDATE programs SET name_en = 'Essay Writing (Malayalam)' WHERE code = 'P-107' AND name_en IS DISTINCT FROM 'Essay Writing (Malayalam)';
UPDATE programs SET name_en = 'Essay Writing (English)' WHERE code = 'P-108' AND name_en IS DISTINCT FROM 'Essay Writing (English)';
UPDATE programs SET name_en = 'Essay Writing (Urdu)' WHERE code = 'P-109' AND name_en IS DISTINCT FROM 'Essay Writing (Urdu)';
UPDATE programs SET name_en = 'Translation (English)' WHERE code = 'P-110' AND name_en IS DISTINCT FROM 'Translation (English)';
UPDATE programs SET name_en = 'Madhu Gana Rachana' WHERE code = 'P-111' AND name_en IS DISTINCT FROM 'Madhu Gana Rachana';
UPDATE programs SET name_en = 'Elocution Malayalam' WHERE code = 'P-031' AND name_en IS DISTINCT FROM 'Elocution Malayalam';
UPDATE programs SET name_en = 'Elocution English' WHERE code = 'P-032' AND name_en IS DISTINCT FROM 'Elocution English';
UPDATE programs SET name_en = 'Madhu Ganam' WHERE code = 'P-034' AND name_en IS DISTINCT FROM 'Madhu Ganam';
UPDATE programs SET name_en = 'Poem Recitation (Arabic)' WHERE code = 'P-035' AND name_en IS DISTINCT FROM 'Poem Recitation (Arabic)';
UPDATE programs SET name_en = 'Poem Recitation (Malayalam)' WHERE code = 'P-036' AND name_en IS DISTINCT FROM 'Poem Recitation (Malayalam)';
UPDATE programs SET name_en = 'Poem Recitation (Urdu)' WHERE code = 'P-037' AND name_en IS DISTINCT FROM 'Poem Recitation (Urdu)';
UPDATE programs SET name_en = 'Story Writing' WHERE code = 'P-039' AND name_en IS DISTINCT FROM 'Story Writing';
UPDATE programs SET name_en = 'Poem Making' WHERE code = 'P-040' AND name_en IS DISTINCT FROM 'Poem Making';
UPDATE programs SET name_en = 'Pencil Drawing' WHERE code = 'P-041' AND name_en IS DISTINCT FROM 'Pencil Drawing';
UPDATE programs SET name_en = 'Water Colouring' WHERE code = 'P-042' AND name_en IS DISTINCT FROM 'Water Colouring';
UPDATE programs SET name_en = 'Essay Writing (Malayalam)' WHERE code = 'P-044' AND name_en IS DISTINCT FROM 'Essay Writing (Malayalam)';
UPDATE programs SET name_en = 'Caption Writing' WHERE code = 'P-046' AND name_en IS DISTINCT FROM 'Caption Writing';
UPDATE programs SET name_en = 'Language Game (English)' WHERE code = 'P-047' AND name_en IS DISTINCT FROM 'Language Game (English)';
UPDATE programs SET name_en = 'Poem Recitation (Urdu)' WHERE code = 'P-054' AND name_en IS DISTINCT FROM 'Poem Recitation (Urdu)';
UPDATE programs SET name_en = 'Bakthi Ganam' WHERE code = 'P-056' AND name_en IS DISTINCT FROM 'Bakthi Ganam';
UPDATE programs SET name_en = 'Elocution' WHERE code = 'P-057' AND name_en IS DISTINCT FROM 'Elocution';
UPDATE programs SET name_en = 'Story Writing' WHERE code = 'P-059' AND name_en IS DISTINCT FROM 'Story Writing';
UPDATE programs SET name_en = 'Poem Making' WHERE code = 'P-060' AND name_en IS DISTINCT FROM 'Poem Making';
UPDATE programs SET name_en = 'Essay Writing (Malayalam)' WHERE code = 'P-061' AND name_en IS DISTINCT FROM 'Essay Writing (Malayalam)';
UPDATE programs SET name_en = 'Essay Writing (English)' WHERE code = 'P-062' AND name_en IS DISTINCT FROM 'Essay Writing (English)';
UPDATE programs SET name_en = 'Pencil Drawing' WHERE code = 'P-064' AND name_en IS DISTINCT FROM 'Pencil Drawing';
UPDATE programs SET name_en = 'Water Colouring' WHERE code = 'P-065' AND name_en IS DISTINCT FROM 'Water Colouring';
UPDATE programs SET name_en = 'Calligraphy (Arabic)' WHERE code = 'P-068' AND name_en IS DISTINCT FROM 'Calligraphy (Arabic)';
UPDATE programs SET name_en = 'Duff (10 members)' WHERE code = 'P-123' AND name_en IS DISTINCT FROM 'Duff (10 members)';
UPDATE programs SET name_en = 'Group Song (Category-A) (4 members)' WHERE code = 'P-125' AND name_en IS DISTINCT FROM 'Group Song (Category-A) (4 members)';
UPDATE programs SET name_en = 'Group Song (Category-B) (4 members)' WHERE code = 'P-126' AND name_en IS DISTINCT FROM 'Group Song (Category-B) (4 members)';
UPDATE programs SET name_en = 'Moulid Recitation (4 members)' WHERE code = 'P-127' AND name_en IS DISTINCT FROM 'Moulid Recitation (4 members)';
UPDATE programs SET name_en = 'Qaseeda Recitation (4 members)' WHERE code = 'P-128' AND name_en IS DISTINCT FROM 'Qaseeda Recitation (4 members)';
UPDATE programs SET name_en = 'Viplava Ganam (3 members)' WHERE code = 'P-129' AND name_en IS DISTINCT FROM 'Viplava Ganam (3 members)';
UPDATE programs SET name_en = 'Chumarezhuth (2 members)' WHERE code = 'P-130' AND name_en IS DISTINCT FROM 'Chumarezhuth (2 members)';
UPDATE programs SET name_en = 'Viplavagana Rachana' WHERE code = 'P-134' AND name_en IS DISTINCT FROM 'Viplavagana Rachana';
UPDATE programs SET name_en = 'Mappilappatt Rachana' WHERE code = 'P-135' AND name_en IS DISTINCT FROM 'Mappilappatt Rachana';
UPDATE programs SET name_en = 'Story Telling' WHERE code = 'P-016' AND name_en IS DISTINCT FROM 'Story Telling';
UPDATE programs SET name_en = 'Elocution' WHERE code = 'P-017' AND name_en IS DISTINCT FROM 'Elocution';
UPDATE programs SET name_en = 'Ganitha Keli' WHERE code = 'P-018' AND name_en IS DISTINCT FROM 'Ganitha Keli';
UPDATE programs SET name_en = 'Pencil Drawing' WHERE code = 'P-020' AND name_en IS DISTINCT FROM 'Pencil Drawing';
UPDATE programs SET name_en = 'Water Colouring' WHERE code = 'P-021' AND name_en IS DISTINCT FROM 'Water Colouring';
UPDATE programs SET name_en = 'Story Writing' WHERE code = 'P-022' AND name_en IS DISTINCT FROM 'Story Writing';
COMMIT;
